### ISSUE TITLE
Does deleting all rows works correctly?

### ISSUE THREAD

**Issue by Dictor** [donjajo/php-jsondb#12]
Hello donjajo!
This library is very useful and thank you for your efforts.
I applied your library to [my project](https://github.com/Dictor/Chintomi) and I experience one strange issue which explain in below.

## Situation
When I use 'delete' action without any 'where' function, nothing happened. But, 'delete' action with 'where' function is perfectly worked. The code in issue is :
```
hnd_json::GetDB()->delete()->from(hnd_json::TABLE_BOOK)->trigger(); //not working
hnd_json::GetDB()->delete()->from(hnd_json::TABLE_BOOK)->where(['book_path' => $path])->trigger(); //working

/*
hnd_json::GetDB() returns my Jajo/JSONDB Object
hnd_json::TABLE_BOOK is const of json file's path
*/
```
 You can see whole code I wrote in [here](https://github.com/Dictor/Chintomi/blob/4454bf808188384a6d2f42ceb5154e0c71042c4b/model/mdl_book.php#L65)

I have the snapshot of JSONDB object when it's executed until 
```
hnd_json::GetDB()->delete()->from(hnd_json::TABLE_BOOK)
```
and it's like image below
![snapshot](https://raw.githubusercontent.com/Dictor/Chintomi/28-feature/jajodb_snapshot.jpg)

Additionally, JSONDB Object in this situation performed serveral 'select' actions..

## Solution?
In my think, condition of if statement in [here](https://github.com/donjajo/php-jsondb/blob/63ca568498dc11ffe8d232258df060c4982a49a3/src/JSONDB.php#L191) need to be changed ' _empty( $this->where ) && empty( $this->last_indexes )_ to _empty( $this->where )_ or _flush_indexes_ function need to be called before every deleting all rows action. But, I didn't understand whole of your code and intentions. so, I just guess

Thank you for reading and I will look forward to your reply.

**Comment by donjajo** [comment]
Hi,
I am unable to replicate your issue. I added a test for delete all here cac01b5df549aa684abd171864b5363cc2c76768 and all works fine. Kindly check and revert.

**Comment by Dictor** [comment]
Hello, thanks for reply.
I updated test for delete all at #13.
In this test case, you can reproduce my issue's situation.

Or, Is it intended to recreate new JSONDB object per each actions?
Please check my pull request and question. Thank you.

**Comment by donjajo** [comment]
This has been fixed here in the above commit.

Thank you!
