### ISSUE TITLE
omit version field from composer.json to automate packagist

### ISSUE THREAD

**Issue by kungknut** [donjajo/php-jsondb#24]
Hi!

As of yesterdays new release I ran composer in order to upgrade to the new version, but it seems to be missing from packagist. I'm no expert in how to publish stuff to packagist but when reading on their websites it says the following;

https://packagist.org/about#managing-package-versions

> The easiest way to manage versioning is to just omit the version field from the composer.json file. The version numbers will then be parsed from the tag and branch names.

It seems like the version field is incorrect in the 2.1 tag and states it is version 2.0. What I understand this error can be easily fixed by just removing one line from composer.json, which in turn will prevent this from happening again. https://github.com/donjajo/php-jsondb/blob/cb40a54191e8ff1e27435575501d53e2807ebe5f/composer.json#L6

**Comment by donjajo** [comment]
Hello!
I am no expert too :)
But I have made the changes. Let me know if this fixes it.

**Comment by kungknut** [comment]
Hi again!
The new version has been published to packagist and it seems to be working fine.
