### ISSUE TITLE
Need more and more time to insert when the json file become biger and biger

### ISSUE THREAD

**Issue by lizhaoyao** [donjajo/php-jsondb#28]
The insertion efficiency is too slow. I executed the following code 10 times, and then found that when the amount of data is more, the efficiency is lower, and the execution time is longer, which is outrageous. I'm just 10000 pieces of data, and I have to execute it for so long. If the amount of data is more, I'm afraid the execution time of PHP will timeout.

Here is the code
```
<?php
use Jajo\JSONDB;
$json_db = new JSONDB( __DIR__ );
$start_time  =  microtime(true);
for ($i=0; $i < 1000; $i++) { 
  $json_db->insert( 'users.json', 
    [ 
      'name' => 'Thomas', 
      'state' => 'Nigeria', 
      'age' => 22 
    ]
  );
}
$end_time  =  microtime(true);
echo (($end_time - $start_time)*1000) . "ms \r\n";
exit;
```
Here is the time-consuming statistics

1. use time 726.8979549408ms

2. use time 1994.8089122772ms

3. use time 3459.1610431671ms

4. use time 4974.9350547791ms

5. use time 6259.6259117126ms

6. use time 7802.2899627686ms

7. use time 9063.7650489807ms

8. use time 10567.301988602ms

9. use time 12003.533124924ms

10. use time 13695.207118988ms

**Comment by donjajo** [comment]
Hi,
Thank you for raising this. I was quite inexperienced when I built this. I know better now, and I have replicated your test.
I will try to make insertion O(1). It makes sense to be that.

**Comment by lizhaoyao** [comment]
I add a function name "append" to insert more than 1 rows data.I think it will be faster than insert
The code is here
```php
	public function append(string $file = '', array $append_data = []) {
		$this->from( $file );
		if (is_array($append_data)) {
			if (!is_array(current($append_data))) {
				$append_data = [$append_data];
			}
			$append_data = json_encode( $append_data, $this->json_opts[ 'encode' ] );
		}

		$f = fopen( $this->file, 'r+' );
		clearstatcache();
		$length  = filesize($this->file);

		if ($this->content) {
			fseek($f, $length - 2);
			$append_data = "," . substr($append_data, 1);
		}
		fwrite( $f, $append_data );
		fclose( $f );
	}
```
The the test code can be here
```php
use Jajo\JSONDB;
$json_db = new JSONDB( __DIR__ );
$start_time  =  microtime(true);
$data = [];
for ($i=0; $i < 1000; $i++) { 
  $data[] = [ 
    'name' => 'Thomas', 
    'state' => 'Nigeria', 
    'age' => 22 
  ];
}
$json_db->append('users.json', $data);
$end_time  =  microtime(true);
echo (($end_time - $start_time)*1000) . "ms \r\n";
```
I executed the following code 10 times
Here is the time-consuming statistics
 1. 0.95391273498535ms 
 2. 2.5191307067871ms 
 3. 7.1418285369873ms 
 4. 10.353088378906ms 
 5. 13.818025588989ms 
 6. 7.2140693664551ms 
 7. 8.2550048828125ms 
 8. 23.193836212158ms 
 9. 15.732049942017ms 
10. 30.563831329346ms

really faster!

**Comment by donjajo** [comment]
Hi @lizhaoyao ,

Your contribution helped me get a better approach after improving it. I made a commit on `dev` branch and the insert time is constant despite the size of the json file :)

You can check it out while I am still running tests.

**Comment by lizhaoyao** [comment]
Thank you. Now I see your new code. It's very good. It solves the problem of slow insertion speed when the JSON file is very large. Of course, this solves the problem of single insert. I think the append method I added helps to solve the problem of batch insert. When we plan to migrate hundreds of thousands of records from the database to this JSON file solution, batch insert is very necessary. Anyway, your code improvement is very good, I also need read your code to learn more knowledge.
