### ISSUE TITLE
My fork php-jsondb 

### ISSUE THREAD

**Issue by nazbav** [donjajo/php-jsondb#6]
Hi, I created a copy of your project and connected the composer there, I would like to hear your opinion:
[nazbav/php-jsondb](https://github.com/nazbav/php-jsondb)

---

Привет, я сделал копию твоего проекта и подключил там композитор, хотелось бы услышать ваше мнение:
[nazbav/php-jsondb](https://github.com/nazbav/php-jsondb)

**Comment by donjajo** [comment]
Nice! I will touch some codes and it up officially on composer though

**Comment by donjajo** [comment]
Here. jajo/jsondb
I did some touches too.
