### ISSUE TITLE
Reset content if file not exists

### ISSUE THREAD

**Issue by kinger-de** [donjajo/php-jsondb#7]
Hi.

If you read multiple files and a file is not exsisting, the function 'check_file' is writing the contents from an previouse read into the new file.
My current sulution is to reset the content before call 'commit' in 'check_file'.
Maybe that is something that you want to update in your sources.

greetings

**Comment by donjajo** [comment]
How are you reading multiple files?

**Comment by kinger-de** [comment]
I have an index file ('./index.js') where you can find the data for all albums, for example. Each album has an ID which I build from the name and more. With this ID, I access the extended information such as the title list ('./{#ID}/song-list.json') by path to other JSON files. I have followed this approach to see if I can save all objects separately. Goes well right now.
What do you think about this approach?

**Comment by donjajo** [comment]
Your issue has been fixed here - 2e3c46c996453bce2ac4eed022eaf92ab93a6392
