### ISSUE TITLE
Unicode unescape

### ISSUE THREAD

**Issue by selfclose** [donjajo/php-jsondb#8]
https://github.com/donjajo/php-jsondb/blob/2e3c46c996453bce2ac4eed022eaf92ab93a6392/src/JSONDB.php#L132

Sometime store and read data in other language it's became ex: "\u0e1a\u0e23"
Can you make an option or unescape them?

```php
fwrite( $f, ( !$this->content ? '[]' : json_encode( $this->content, JSON_UNESCAPED_UNICODE ) ) ); 
```

Thanks :)

**Comment by donjajo** [comment]
Thank you for pointing this out! It has been added here 1b6ebdd31dae4492f7b07555fb96d6d62940a325
